name: halloween
description: Halloween project for Pragma SA
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ^2.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  rxdart: ^0.27.2
  url_launcher: ^6.0.12
  youtube_player_iframe: ^2.2.2
  camera: ^0.9.4+3
  video_player: ^2.2.5
  firebase_core: ^1.8.0
  firebase_storage: ^10.0.6
  animate_do: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins.ttf